security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'bcrypt'

    providers:
        user_provider:
            entity:
                class: App\Model\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: user_provider
            form_login:
                username_parameter: email
                password_parameter: password
                login_path: auth_login
                check_path: auth_login
                enable_csrf: true
            logout:
                path: /auth/logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800

    # ðŸš¨ Ces rÃ¨gles doivent Ãªtre ici (section *globale*, pas dans when@test)
    access_control:
        - { path: ^/auth/register$, roles: PUBLIC_ACCESS }
        - { path: ^/auth/login$, roles: PUBLIC_ACCESS }


when@test:
    security:
        firewalls:
            main:
                stateless: false
                lazy: true

        # NE PAS redÃ©finir access_control ici
        # password hash plus rapide pour tests
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
