name: CI Symfony (PHPStan + PHPUnit)

on:
    push:
        branches: [ main, devuser, versbeta ]
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest

        env:
            APP_ENV: test
            DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data/test.db"

        steps:

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Debug workspace
              run: pwd && ls -R .

            - name: Setup PHP 8.4
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.4'
                  extensions: intl, mbstring, sqlite, pdo_sqlite
                  tools: composer:v2

            - name: Install dependencies (no scripts)
              run: composer install --no-interaction --no-progress --no-scripts

            - name: Ensure SQLite DB exists
              run: |
                  mkdir -p var/data
                  touch var/data/test.db
                  chmod -R 777 var/data
                  ls -l var/data

            - name: Prepare SQLite database
              run: |
                  php bin/console doctrine:schema:create --env=test
                  php bin/console doctrine:fixtures:load --env=test --no-interaction

            - name: Run PHPStan
              run: vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=1G --no-progress

            - name: Run PHPUnit
              run: php bin/phpunit --testdox --colors=always
