name: CI Symfony (PHPStan + PHPUnit)

on:
    push:
        branches:
            - main
            - devuser
            - versbeta
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:

            # Checkout du code
            - name: Checkout repository
              uses: actions/checkout@v4

            # Configuration PHP
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.4'
                  extensions: intl, mbstring, pdo_mysql
                  tools: composer:v2
                  coverage: none

            # Installation des dépendances sinon problème mysql SANS scripts (évite cache:clear)
            - name: Install Dependencies (no scripts)
              run: composer install --no-progress --no-interaction --no-scripts
              working-directory: ${{ github.workspace }}

            # Debug : montre les fichiers réellement présents sur GitHub
            - name: Debug listing
              run: ls -la
              working-directory: ${{ github.workspace }}

            # Analyse PHPStan
            - name: Run PHPStan (force correct config)
              run: vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=1G --no-progress
              working-directory: ${{ github.workspace }}

            # Préparation BDD test
            - name: Create test database
              run: |
                  php bin/console doctrine:database:create --env=test
                  php bin/console doctrine:migrations:migrate --env=test -n
              working-directory: ${{ github.workspace }}

            # Exécution PHPUnit
            - name: Run PHPUnit
              run: symfony php bin/phpunit --colors=always
              working-directory: ${{ github.workspace }}
